import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { AlertCircle, ArrowLeft, CheckCircle2, Circle, FileUp, Loader2, Save, ShieldCheck, UsersRound } from 'lucide-react';
import axios from 'axios';
import { PIPELINE_STAGES } from './onboarding/config';

const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
const OnboardingTracker = () => {
  const { clientId, onboardingId } = useParams(); const navigate = useNavigate();
  const [record, setRecord] = useState(null); const [staff, setStaff] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const [stage, setStage] = useState('stage_1'); const [advance, setAdvance] = useState(false); const [lostReason, setLostReason] = useState(''); const [reengagementDate, setReengagementDate] = useState(''); const [auditPartner, setAuditPartner] = useState(''); const [auditManager, setAuditManager] = useState('');
  const load = async () => { try { const target = onboardingId ? `${API}/onboarding/${onboardingId}` : `${API}/onboarding/client/${clientId}`; const response = await axios.get(target, { withCredentials: true }); let data = response.data; if (Array.isArray(data)) { const latest = data[0]; data = latest ? (await axios.get(`${API}/onboarding/${latest.onboarding_id}`, { withCredentials: true })).data : null; } if (!data) { setMessage('No service onboarding record exists for this client.'); return; } setRecord(data); setStage(data.pipeline_stage); setAdvance(data.advance_payment_confirmed || false); setLostReason(data.lost_reason || ''); setReengagementDate(data.re_engagement_date || ''); setAuditPartner(data.audit_partner || ''); setAuditManager(data.audit_manager || ''); } catch (error) { setMessage(error.response?.data?.detail || 'Unable to load the onboarding tracker.'); } finally { setLoading(false); } };
  useEffect(() => { load(); axios.get(`${API}/auth/users-list`, { withCredentials: true }).then(response => setStaff(response.data)).catch(() => {}); }, [onboardingId, clientId]);
  const updateStage = async () => { if (!record) return; setSaving(true); setMessage(''); try { await axios.patch(`${API}/onboarding/${record.onboarding_id}`, { pipeline_stage: stage, advance_payment_confirmed: advance, lost_reason: lostReason || null, re_engagement_date: reengagementDate || null, audit_partner: auditPartner || null, audit_manager: auditManager || null }, { withCredentials: true }); setMessage('Pipeline stage saved. The checklist now reflects the active stage.'); await load(); } catch (error) { setMessage(error.response?.data?.detail || 'Unable to update this service pipeline.'); } finally { setSaving(false); } };
  const upload = async (label, file) => { if (!file || !record) return; setMessage(''); const body = new FormData(); body.append('file', file); try { await axios.post(`${API}/onboarding/${record.onboarding_id}/documents?document_label=${encodeURIComponent(label)}`, body, { withCredentials: true, headers: { 'Content-Type': 'multipart/form-data' } }); setMessage(`${label} uploaded.`); await load(); } catch (error) { setMessage(error.response?.data?.detail || 'Upload failed.'); } };
  if (loading) return <div style={styles.loading} data-testid="onboarding-tracker-loading"><Loader2 className="spin" /> Loading service tracker…</div>;
  if (!record) return <div style={styles.loading} data-testid="onboarding-tracker-empty">{message || 'No onboarding record found.'}</div>;
  const stageInfo = PIPELINE_STAGES.find(item => item.id === record.pipeline_stage);
  return <div className="fade-in" data-testid="onboarding-tracker-page"><button onClick={() => navigate('/app/client-master')} className="tbtn tbtn-outline" style={styles.back} data-testid="onboarding-tracker-back"><ArrowLeft size={14} /> Client Master</button><header style={styles.header}><div><div style={styles.eyebrow}>Service pipeline · {record.crm_sheet}</div><h1 style={styles.heading}>{record.name}</h1><p style={styles.subhead}>{record.service_type} · {stageInfo?.label}</p></div><div style={styles.id} data-testid="onboarding-tracker-client-id">{record.client_id}</div></header>
    <div style={styles.layout}><section className="nn-card" style={styles.card}><h2 style={styles.title}>Stage tracker</h2><p style={styles.muted}>Update the current stage to refresh actions and required document slots.</p><div style={styles.stageList} data-testid="onboarding-stage-progress">{PIPELINE_STAGES.map((item, index) => { const activeIndex = PIPELINE_STAGES.findIndex(current => current.id === record.pipeline_stage); const completed = index < activeIndex; const active = item.id === record.pipeline_stage; return <div key={item.id} style={styles.stageRow} data-testid={`pipeline-stage-${item.id}`}>{completed ? <CheckCircle2 size={17} color="var(--green)" /> : active ? <AlertCircle size={17} color="var(--gold4)" /> : <Circle size={17} color="var(--light)" />}<span style={{ color: active ? 'var(--text)' : 'var(--muted)', fontWeight: active ? 700 : 400 }}>{item.label}</span></div>; })}</div></section>
      <section className="nn-card" style={styles.card}><h2 style={styles.title}>Advance the pipeline</h2><div style={styles.formGrid}><Field label="Current Status"><select value={stage} onChange={event => setStage(event.target.value)} style={styles.input} data-testid="onboarding-tracker-stage-select">{PIPELINE_STAGES.map(item => <option key={item.id} value={item.id}>{item.label}</option>)}</select></Field>{(stage === 'stage_4' || stage === 'stage_5') && <label style={styles.check}><input type="checkbox" checked={advance} onChange={event => setAdvance(event.target.checked)} data-testid="onboarding-advance-payment-confirmed" /> Advance payment status confirmed</label>}{stage === 'stage_6' && <><Field label="Lost Reason"><select value={lostReason} onChange={event => setLostReason(event.target.value)} style={styles.input} data-testid="onboarding-lost-reason"><option value="">Select a reason...</option>{['High Fee','Competitor','No Response','Other'].map(item => <option key={item}>{item}</option>)}</select></Field><Field label="Re-engagement Date"><input type="date" value={reengagementDate} onChange={event => setReengagementDate(event.target.value)} style={styles.input} data-testid="onboarding-reengagement-date" /></Field></>}{stage === 'stage_5' && <><Field label="Audit Partner"><select value={auditPartner} onChange={event => setAuditPartner(event.target.value)} style={styles.input} data-testid="onboarding-audit-partner"><option value="">Assign later</option>{staff.map(item => <option key={item.email} value={item.email}>{item.name}</option>)}</select></Field><Field label="Audit Manager"><select value={auditManager} onChange={event => setAuditManager(event.target.value)} style={styles.input} data-testid="onboarding-audit-manager"><option value="">Assign later</option>{staff.map(item => <option key={item.email} value={item.email}>{item.name}</option>)}</select></Field></>}<button onClick={updateStage} disabled={saving} className="tbtn tbtn-gold" style={styles.save} data-testid="onboarding-save-stage">{saving ? <Loader2 size={14} className="spin" /> : <Save size={14} />} Save pipeline</button></div></section>
      <section className="nn-card" style={{ ...styles.card, gridColumn: '1 / -1' }}><h2 style={styles.title}>Required actions & documents</h2><p style={styles.muted} data-testid="onboarding-stage-action">{record.stage_tracker?.action}</p>{record.stage_tracker?.requires_advance_confirmation && <div style={styles.warning} data-testid="onboarding-advance-warning"><ShieldCheck size={16} /> Confirm advance payment before moving to Stage 5.</div>}{record.stage_tracker?.requires_lost_reason && <div style={styles.warning} data-testid="onboarding-lost-reason-warning"><AlertCircle size={16} /> Select a lost reason to save Stage 6.</div>}<div style={styles.docs}>{(record.stage_tracker?.documents || []).length === 0 ? <span style={styles.muted}>No document upload is required at this stage.</span> : record.stage_tracker.documents.map(label => { const uploaded = record.documents?.find(item => item.document_label === label); return <div style={styles.docRow} key={label} data-testid={`onboarding-document-${label.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`}><div>{uploaded ? <CheckCircle2 size={18} color="var(--green)" /> : <FileUp size={18} color="var(--gold4)" />}</div><div style={{ flex: 1 }}><div style={styles.docLabel}>{label}</div><div style={styles.docMeta}>{uploaded ? `Uploaded: ${uploaded.original_filename}` : 'Upload required'}</div></div><label className="tbtn tbtn-outline" style={styles.uploadLabel} data-testid={`onboarding-upload-${label.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`}>Upload<input type="file" onChange={event => upload(label, event.target.files?.[0])} style={{ display: 'none' }} data-testid={`onboarding-file-${label.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`} /></label></div>; })}</div></section>
    </div>{message && <div style={message.includes('Unable') || message.includes('before') || message.includes('reason') ? styles.error : styles.success} data-testid="onboarding-tracker-message">{message}</div>}</div>;
};
const Field = ({ label, children }) => <div><label style={styles.label}>{label}</label>{children}</div>;
const styles = { loading: { padding: 50, color: 'var(--muted)', display: 'flex', justifyContent: 'center', gap: 8 }, back: { marginBottom: 14, display: 'inline-flex', alignItems: 'center', gap: 6 }, header: { background: 'linear-gradient(125deg, var(--navy), var(--navy3))', padding: '27px 30px', display: 'flex', justifyContent: 'space-between', gap: 20, flexWrap: 'wrap', marginBottom: 18 }, eyebrow: { color: 'var(--gold)', fontSize: 10, textTransform: 'uppercase', letterSpacing: 1.1, fontWeight: 700 }, heading: { margin: '6px 0', color: 'var(--gold)', fontFamily: 'DM Serif Display', fontSize: 28 }, subhead: { color: 'rgba(255,255,255,.66)', margin: 0, fontSize: 13 }, id: { color: 'var(--gold)', border: '1px solid rgba(212,175,55,.35)', padding: '8px 10px', height: 'fit-content', fontFamily: 'monospace', fontSize: 11 }, layout: { display: 'grid', gridTemplateColumns: 'minmax(260px, .75fr) minmax(360px, 1.25fr)', gap: 18 }, card: { padding: 22 }, title: { fontFamily: 'DM Serif Display', color: 'var(--text)', margin: 0, fontSize: 19 }, muted: { fontSize: 12, color: 'var(--muted)', lineHeight: 1.5, margin: '6px 0 0' }, stageList: { display: 'grid', gap: 12, marginTop: 20 }, stageRow: { display: 'flex', gap: 9, alignItems: 'center', fontSize: 12, lineHeight: 1.3 }, formGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))', gap: 14, marginTop: 18, alignItems: 'end' }, label: { display: 'block', marginBottom: 6, color: 'var(--muted)', textTransform: 'uppercase', letterSpacing: .5, fontSize: 10, fontWeight: 700 }, input: { width: '100%', boxSizing: 'border-box', padding: '10px 11px', background: 'var(--white)', border: '1px solid var(--nn-border)', borderRadius: 'var(--rs)', color: 'var(--text)', fontFamily: 'DM Sans', fontSize: 12 }, check: { gridColumn: '1 / -1', display: 'flex', gap: 8, fontSize: 12, color: 'var(--text)', alignItems: 'center', cursor: 'pointer' }, save: { width: 'fit-content', display: 'inline-flex', alignItems: 'center', gap: 7 }, warning: { display: 'flex', gap: 8, alignItems: 'center', fontSize: 12, padding: '9px 11px', color: '#a16207', background: 'rgba(245,158,11,.09)', marginTop: 15 }, docs: { display: 'grid', gap: 8, marginTop: 18 }, docRow: { display: 'flex', alignItems: 'center', gap: 11, padding: '12px 0', borderBottom: '1px solid var(--nn-border)' }, docLabel: { fontSize: 13, fontWeight: 600, color: 'var(--text)' }, docMeta: { fontSize: 11, color: 'var(--muted)', marginTop: 3 }, uploadLabel: { cursor: 'pointer', fontSize: 11 }, success: { marginTop: 16, padding: '10px 12px', background: 'var(--green-bg)', color: 'var(--green)', fontSize: 12 }, error: { marginTop: 16, padding: '10px 12px', background: 'var(--red-bg)', color: 'var(--red)', fontSize: 12 } };
export default OnboardingTracker;